### ISSUE TITLE
Set up documentation

### ISSUE THREAD

**Issue by timothyquach** [ferdx/ferdx#1]

**Comment by gartenfeld** [comment]
> "Document your project and codebase to the point that if you decide to push it to hacker-news, anyone with a solid understanding of JavaScript can (after reviewing your documentation and comments) start submitting pull requests. Plan on not having any face-to-face interaction with the next team of collaborators. The most effective and efficient way to accomplish this is to do it right from the very start."

**Comment by gartenfeld** [comment]
* Add Style Guide
* Add Contribution Guide
